type:
    exercises: APE
    errata: Books
    notes: CM
    summary: Synthèses
    formulaire: Formulaires
    mcq: APE
    exam: Examens
    test: Interros
quadri:
    1: BACHELIER
    2: BACHELIER
    3: BACHELIER
    4: BACHELIER
    5: BACHELIER
    6: BACHELIER
    7: MASTER
    8: MASTER
option:
    FSAB: Tronc commun
    EPL: Tronc commun
    AUCE: GCIV
    BIR: Mineures externes
    ECGE: Mineures externes
    ELEC: ELEC
    GCIV: GCIV
    ICAR: GCIV
    INGI: INFO
    INMA: MAP
    LSMG: LSMG
    MAPR: FYKI
    MAT: MAT
    MECA: MECA
    SINF: INFO
    FSA: FSA
    PHYS: PHYS
name:
    advsecu: Secured systems engineering
    advalgo: Advanced Algorithms for Optimization
    aerodyn: Aerospace dynamics
    algebre: Algèbre
    analyse: Analyse
    algo: Algorithmique et structures de données
    analog: Design and Architecture of analog electronic systems
    ananum: Analyse numérique
    archi: Architecture and performance of computer systems
    autoindu: Industrial automation
    autolin: Automatique linéaire
    calcu: Calculabilité
    chimie: Chimie
    chimieorga: Chimie Organique
    cinchim: Cinétique physique et chimique
    circ: Circuits électroniques analogiques et digitaux
    circmes: Circuits et Mesures
    cl: Computational Linguistics
    cloud: Cloud Computing
    combu: Combustion and fuels
    complanal: Complément d'analyse
    complelec: Compléments d'électricité
    compta: Gestion financière et comptable
    concurrent: Concurrent Systems
    constraint: Constraint Programming
    conv: Convertisseurs électromécaniques
    converto2: Dynamic modelling and control of electromechanical converters
    coo: Conception orientée objet et gestion de données
    crypto: Cryptography
    dam: DAM
    database: Databases
    devmeth: Software Quality Assurance
    digitalsynthesis: Synthesis of digital integrated circuits
    dispo: Dispositifs électroniques
    distributed: Languages and algorithms for distributed applications
    eco: Économie
    ecopol: Economie politique
    edifsout: Edification soutenable
    edo: Equations différentielles ordinaires
    edp: EDPs et analyse complexe
    elec: Physique
    embedded: Mobile and embedded computing
    embeddedsyst: Design of embedded and real-time systems
    fabmeca: Fabrication mécanique
    fem: Eléments Finis
    fmt: Fluids Mechanics and Transfers II
    gameth: Game Theory
    geomat: Géomatériaux
    geotechnics: Geotechnics
    geotechdesign: Geotechnical Design
    gpo: Gestion de production et des opérations
    grh: Organisation et ressources humaines
    hydrau: Hydraulique
    ia: Artificial Intelligence
    ice: Internal combustion engines
    info: Informatique
    infoth: Information theory and coding
    introtelecom: Introduction aux télécommunications
    instrusensors: Instrumentation & Sensors
    logique: Logique et structures discrètes
    magn: Electromagnétisme
    mana: Management humain
    math: Mathématiques
    matrix: Matrix computations
    matstruct: Matériaux structuraux
    maintenance: Software Maintenance and Evolution
    mcp: Méthodes de conception de programmes
    meca: Physique
    mecasols: Mécanique des sols
    methodnum: Méthodes numériques
    mft: Mécanique des Fluides et Transferts
    ml: Machine Learning
    mmc: Mécanique des Milieux Continus
    modstoch: Stochastic Modelling
    msd: Mécanique des Solides Déformables
    network: Réseaux informatiques
    network2: Computer networks
    nlp: Nonlinear programming
    numGeo: Numerical Geometry
    numth: Number theory
    offshoregeotech: Offshore Geotechnics
    opti: Modèles et méthodes d'optimisation
    opti2: Optimization models and methods II
    opticombi: Combinatorial optimization
    opticslasers: Optics and lasers
    os: Systèmes informatiques
    oz: Computer language concepts
    paradigms: Programming paradigms
    philo: Philosophie
    physique: Physique
    physmat: Physique des matériaux
    picem: Physics of Electromechanical Converters
    powerelec: Power Electronics
    progmeth: Programming methods
    projet: Projet
    projetelec: Projet
    prostoch: Processus stochastiques
    radiation: Radiation and communication systems
    secu: Computer System Security
    sigproc: Signal processing
    sigsys: Signaux & Systèmes
    stat: Probabilité et statistiques
    strat: Stratégies d'entreprises
    tdg: Théorie et algorithmique des graphes
    tdo: Théorie des organisations
    telecom: Télécommunications
    thermo: Thermodynamique et énergétique
    translators: Languages and Translators
    relatrestreinte: Relativité restreinte
