input_base: .
output_base: /home/blegat/gdrive
clients:
  - name: EPL-Drive
    arguments:
      quadri: &quadris
        [1, 2, 3, 4, 5, 6, 7, 8]
      name: &names
        - advSecu
        - advalgo
        - algo
        - ananum
        - archi
        - autolin
        - ca
        - calcu
        - chimie
        - chimieorga
        - circ
        - circmes
        - cl
        - cloud
        - concurrent
        - constraint
        - conv
        - coo
        - crypto
        - dam
        - database
        - devmeth
        - dispo
        - distributed
        - eco
        - edo
        - elec
        - embedded
        - fem
        - gameth
        - geomat
        - gpo
        - grh
        - hydrau
        - ia
        - info
        - infoth
        - logique
        - magn
        - mana
        - math
        - matrix
        - matstruct
        - maintenance
        - mcp
        - meca
        - methodnum
        - ml
        - mmc
        - modstoch
        - network
        - nlp
        - numGeo
        - numth
        - opti
        - opticombi
        - os
        - oz
        - paradigms
        - philo
        - physique
        - progmeth
        - projet
        - prostoch
        - secu
        - sigsys
        - stat
        - strat
        - tdo
        - telecom
        - translators
      option: &options
        - FSAB
        - AUCE
        - BIR
        - ECGE
        - ELEC
        - INGI
        - INMA
        - LSMG
        - MAPR
        - MAT
        - MECA
        - SINF
      code: &codes
        - 1031
        - 1101
        - 1102
        - 1103
        - 1104
        - 1105
        - 1106
        - 1113
        - 1120
        - 1121
        - 1122
        - 1123
        - 1131
        - 1152
        - 1170
        - 1171
        - 1201
        - 1202
        - 1203
        - 1210
        - 1223
        - 1225
        - 1230
        - 1252
        - 1301
        - 1302
        - 1304
        - 1310
        - 1315
        - 1317
        - 1321
        - 1330
        - 1341
        - 1350
        - 1370
        - 1401
        - 1402
        - 1503
        - 1510
        - 1530
        - 1702
        - 1731
        - 1802
        - 1803
        - 1901
        - 1930
        - 2004
        - 2132
        - 2142
        - 2143
        - 2144
        - 2145
        - 2146
        - 2170
        - 2172
        - 2224
        - 2241
        - 2251
        - 2252
        - 2261
        - 2263
        - 2266
        - 2335
        - 2345
        - 2347
        - 2348
        - 2365
        - 2380
        - 2440
        - 2450
        - 2460
        - 2470
        - 2471
        - 2760
        - 2870
      type:
        - exercises
        - errata
        - formulaire
        - mcq
        - notes
        - summary
      sol: ['', '-Sol']
      num: ['', '1', '2']
    input:
      path_format: "q{0}/{1}/{2}{4}/{1}-{2}{3}.pdf"
      parameters:
        - arg: quadri
        - &cours
          path_format: "{0}-{1}{2}"
          parameters:
            - arg: name
            - arg: option
            - arg: code
        - arg: type
        - arg: sol
        - arg: num
    output:
      path_format: "EPL-Drive/{0}/{1}/{2}"
      parameters:
        - &start
          path_format: "{0}/{1}/Q{2}/L{3}{4} - {5}"
          parameters:
            - mapping:
                1: BACHELIER
                2: BACHELIER
                3: BACHELIER
                4: BACHELIER
                5: BACHELIER
                6: BACHELIER
                7: MASTER
                8: MASTER
              key:
                arg: quadri
            - mapping:
                FSAB: Tronc commun
                AUCE: GCE
                BIR: INFO
                ECGE: INFO
                ELEC: ELEC
                INGI: INFO
                INMA: MAP
                LSMG: INFO
                MAPR: FYKI
                MAT: MAP
                MECA: MECA
                SINF: INFO
              key:
                arg: option
            - arg: quadri
            - arg: option
            - arg: code
            - mapping:
                advSecu: Secured systems engineering
                advalgo: Advanced Algorithms for Optimization
                algo: Algorithmique et structures de données
                ananum: Analyse numérique
                archi: Architecture and performance of computer systems
                autolin: Automatique Linéaire
                ca: Complément d'analyse
                calcu: Calculabilité
                chimie: Chimie
                chimieorga: Chimie Organique
                circ: Circuits électroniques
                circmes: Circuits et Mesures
                cl: Computational Linguistics
                cloud: Cloud Computing
                concurrent: Concurrent Systems
                constraint: Constraint Programming
                conv: Convert. électrom
                coo: Conception orientée objet et gestion de données
                crypto: Cryptography
                dam: DAM
                database: Databases
                devmeth: "Software Engineering: Development Methods"
                dispo: Dispositifs électroniques
                distributed: Languages and algorithms for distributed applications
                eco: Économie de l'entreprise
                edo: Equations différentielles ordinaires
                elec: Physique
                embedded: Software and operating systems for embedded systems
                gameth: Game Theory
                geomat: Géomatériaux
                gpo: Gestion de production et des opérations
                grh: Gestion des ressources humaines
                hydrau: Hydraulique
                ia: Artificial Intelligence
                info: Informatique
                infoth: Information theory and coding
                logique: Logique et structure discrètes
                magn: Electromagnétisme
                mana: Management humain
                math: Mathématiques
                matrix: Matrix Theory
                matstruct: Matériaux structuraux
                maintenance: Software Maintenance and Evolution
                mcp: Méthodes de conception de programmes
                meca: Physique
                methodnum: Méthodes Numériques
                ml: Machine Learning
                mmc: Mécanique des Milieux Continus
                modstoch: Stochastic Modelling
                network: Réseaux informatiques
                nlp: Nonlinear programming
                numGeo: Numerical Geometry
                numth: Number Theory
                opti: Modèles et méthodes d'optimisation
                opticombi: Integer Programming and Combinatorial Optimisation
                os: Systèmes informatiques
                oz: Computer language concepts
                paradigms: Programming paradigms
                philo: Philosophie
                physique: Physique
                progmeth: Programming methods
                projet: Projet
                prostoch: Stochastic Processes
                secu: Computer System Security
                sigsys: Signaux & Systèmes
                stat: Probabilité et statistiques
                strat: Stratégies d'entreprises
                tdo: Théorie des organisations
                telecom: Télécommunications
                translators: Languages and Translators
              key:
                arg: name
        - mapping:
            exercises: APE
            errata: Books
            notes: CM
            summary: Synthèses
            formulaire: Formulaires
            mcq: APE
          key:
            arg: type
        - path_format: "{0}{1}-{2}-{3}{4}{5}.pdf"
          parameters:
            - mapping:
                exercises: APE
                notes: CM
                summary: Synthèse
              key:
                arg: type
            - arg: num
            - arg: name
            - arg: option
            - arg: code
            - arg: sol

  - name: EPL-Drive exam
    arguments:
      quadri: *quadris
      name: *names
      option: *options
      code: *codes
      type: [exam,test]
      year:
        [2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018]
      month:
        [Janvier, Mars, Juin, Août, Novembre]
      minmaj:
        [All, Mineure, Majeure]
      sol:
        ['', '-Sol']
    input:
      path_format: "q{0}/{1}/{2}/{3}/{4}/{5}/{1}-{2}-{3}-{4}-{5}{6}.pdf"
      parameters:
        - arg: quadri
        - *cours
        - arg: type
        - arg: year
        - arg: month
        - arg: minmaj
        - arg: sol
    output:
      path_format: "EPL-Drive/{0}/{1}/{2}"
      parameters:
        - *start
        - mapping:
            exam: Examens
            test: Interros
          key:
            arg: type
        - path_format: "{0}_{1}/{4}{5}-{0}-{1}{2}{3}.pdf"
          parameters:
          - arg: year
          - arg: month
          - mapping:
              All: ''
              Mineure: -Mineure
              Majeure: -Majeure
            key:
              arg: minmaj
          - arg: sol
          - arg: option
          - arg: code
