input_base: .
output_base: /home/blegat/gdrive
clients:
  - name: EPL-Drive
    arguments:
      quadri: &quadris
        [1, 2, 3, 4, 5, 6, 7, 8]
      name: &names
        - advSecu
        - advalgo
        - algo
        - ananum
        - archi
        - autolin
        - calcu
        - chimie
        - chimieorga
        - cinchim
        - circ
        - circmes
        - cl
        - cloud
        - complanal
        - complelec
        - concurrent
        - constraint
        - conv
        - coo
        - crypto
        - dam
        - database
        - devmeth
        - dispo
        - distributed
        - eco
        - ecopol
        - edifsout
        - edo
        - elec
        - embedded
        - embeddedsyst
        - fabmeca
        - fem
        - gameth
        - geomat
        - gpo
        - grh
        - hydrau
        - ia
        - info
        - infoth
        - introtelecom
        - logique
        - magn
        - mana
        - math
        - matrix
        - matstruct
        - maintenance
        - mcp
        - mft
        - meca
        - mecasols
        - methodnum
        - ml
        - mmc
        - modstoch
        - msd
        - network
        - nlp
        - numGeo
        - numth
        - opti
        - opticombi
        - os
        - oz
        - paradigms
        - philo
        - physique
        - progmeth
        - projet
        - projetelec
        - prostoch
        - secu
        - sigsys
        - stat
        - strat
        - tdo
        - telecom
        - translators
      option: &options
        - FSAB
        - EPL
        - AUCE
        - EPL
        - GCIV
        - BIR
        - ECGE
        - ELEC
        - ICAR
        - INGI
        - INMA
        - LSMG
        - MAPR
        - MAT
        - MECA
        - SINF
      code: &codes
        - 1031
        - 1100
        - 1101
        - 1102
        - 1103
        - 1104
        - 1105
        - 1106
        - 1113
        - 1115
        - 1120
        - 1121
        - 1122
        - 1123
        - 1131
        - 1152
        - 1170
        - 1171
        - 1201
        - 1202
        - 1203
        - 1210
        - 1223
        - 1225
        - 1230
        - 1252
        - 1301
        - 1302
        - 1304
        - 1310
        - 1315
        - 1317
        - 1321
        - 1330
        - 1341
        - 1350
        - 1360
        - 1370
        - 1401
        - 1402
        - 1503
        - 1510
        - 1530
        - 1691
        - 1702
        - 1731
        - 1755
        - 1802
        - 1803
        - 1821
        - 1901
        - 1930
        - 1961
        - 2004
        - 2132
        - 2142
        - 2143
        - 2144
        - 2145
        - 2146
        - 2170
        - 2172
        - 2224
        - 2241
        - 2251
        - 2252
        - 2261
        - 2263
        - 2266
        - 2315
        - 2322
        - 2335
        - 2345
        - 2347
        - 2348
        - 2365
        - 2380
        - 2440
        - 2450
        - 2460
        - 2470
        - 2471
        - 2760
        - 2830
        - 2870
      type:
        - exercises
        - errata
        - formulaire
        - mcq
        - notes
        - summary
      sol: ['', '-Sol']
      num: ['', '1', '2']
    input:
      path_format: "q{0}/{1}/{2}{4}/{1}-{2}{3}.pdf"
      parameters:
        - arg: quadri
        - &cours
          path_format: "{0}-{1}{2}"
          parameters:
            - arg: name
            - arg: option
            - arg: code
        - arg: type
        - arg: sol
        - arg: num
    output:
      path_format: "EPL-Drive/{0}/{1}/{2}"
      parameters:
        - &start
          path_format: "{0}/{1}/Q{2}/L{3}{4} - {5}"
          parameters:
            - mapping:
                1: BACHELIER
                2: BACHELIER
                3: BACHELIER
                4: BACHELIER
                5: BACHELIER
                6: BACHELIER
                7: MASTER
                8: MASTER
              key:
                arg: quadri
            - mapping:
                FSAB: Tronc commun
                EPL: Tronc commun
                AUCE: GCE
                BIR: Mineures externes
                ECGE: Mineures externes
                ELEC: ELEC
                GCIV: GCE
                ICAR: GCE
                INGI: INFO
                INMA: MAP
                LSMG: LSMG
                MAPR: FYKI
                MAT: MAT
                MECA: MECA
                SINF: INFO
                FSA: FSA
              key:
                arg: option
            - arg: quadri
            - arg: option
            - arg: code
            - mapping:
                advSecu: Secured systems engineering
                advalgo: Advanced Algorithms for Optimization
                aerodyn: Aerospace dynamics
                algo: Algorithmique et structures de données
                analog: Design and Architecture of analog electronic systems
                ananum: Analyse numérique
                archi: Architecture and performance of computer systems
                autolin: Automatique linéaire
                calcu: Calculabilité
                chimie: Chimie
                chimieorga: Chimie Organique
                cinchim: Cinétique physique et chimique
                circ: Circuits électroniques analogiques et digitaux
                circmes: Circuits et Mesures
                cl: Computational Linguistics
                cloud: Cloud Computing
                complanal: Complément d'analyse
                complelec: Compléments d'électricité
                compta: Gestion financière et comptable
                concurrent: Concurrent Systems
                constraint: Constraint Programming
                conv: Convertisseurs électromagnétiques
                coo: Conception orientée objet et gestion de données
                crypto: Cryptography
                dam: DAM
                database: Databases
                devmeth: "Software Engineering Development Methods"
                dispo: Dispositifs électroniques
                distributed: Languages and algorithms for distributed applications
                eco: Économie de l'entreprise
                ecopol: Economie politique
                edifsout: Edification soutenable 
                edo: Equations différentielles ordinaires
                elec: Physique
                embedded: Mobile and embedded computing
                embeddedsyst: Design of embedded and real-time systems
                fabmeca: Fabrication mécanique
                fem: Eléments Finis
                fmt: Fluids Mechanics and Transfers II
                gameth: Game Theory
                geomat: Géomatériaux
                gpo: Gestion de production et des opérations
                grh: Organisation et ressources humaines
                hydrau: Hydraulique
                ia: Artificial Intelligence
                info: Informatique
                infoth: Information theory and coding
                introtelecom: Introduction aux télécommunications
                logique: Logique et structures discrètes
                magn: Electromagnétisme
                mana: Management humain
                math: Mathématiques
                matrix: Matrix computations
                matstruct: Matériaux structuraux
                maintenance: Software Maintenance and Evolution
                mcp: Méthodes de conception de programmes
                meca: Physique
                mecasols: Mécanique des sols
                methodnum: Méthodes numériques
                mft: Mécanique des Fluides et Transferts
                ml: Machine Learning
                mmc: Mécanique des Milieux Continus
                modstoch: Stochastic Modelling
                msd: Mécanique des Solides Déformables
                network: Réseaux informatiques
                nlp: Nonlinear programming
                numGeo: Numerical Geometry
                numth: Number theory
                opti: Modèles et méthodes d'optimisation
                opti2: Optimization models and methods II
                opticombi: Combinatorial optimization
                os: Systèmes informatiques
                oz: Computer language concepts
                paradigms: Programming paradigms
                philo: Philosophie
                physique: Physique
                physmat: Physique des matériaux
                progmeth: Programming methods
                projet: Projet
                projetelec: Projet
                prostoch: Processus stochastiques
                secu: Computer System Security
                sigsys: Signaux & Systèmes
                stat: Probabilité et statistiques
                strat: Stratégies d'entreprises
                tdg: Théorie et algorithmie des graphes
                tdo: Théorie des organisations
                telecom: Télécommunications
                thermo: Thermodynamique et énergétique
                translators: Languages and Translators
              key:
                arg: name
        - mapping:
            exercises: APE
            errata: Books
            notes: CM
            summary: Synthèses
            formulaire: Formulaires
            mcq: APE
          key:
            arg: type
        - path_format: "{0}{1}-{2}-{3}{4}{5}.pdf"
          parameters:
            - mapping:
                exercises: APE
                notes: CM
                summary: Synthèse
              key:
                arg: type
            - arg: num
            - arg: name
            - arg: option
            - arg: code
            - arg: sol

  - name: EPL-Drive exam
    arguments:
      quadri: *quadris
      name: *names
      option: *options
      code: *codes
      type: [exam,test]
      year:
        [2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018]
      month:
        [Janvier, Mars, Juin, Août, Novembre]
      minmaj:
        [All, Mineure, Majeure]
      sol:
        ['', '-Sol']
    input:
      path_format: "q{0}/{1}/{2}/{3}/{4}/{5}/{1}-{2}-{3}-{4}-{5}{6}.pdf"
      parameters:
        - arg: quadri
        - *cours
        - arg: type
        - arg: year
        - arg: month
        - arg: minmaj
        - arg: sol
    output:
      path_format: "EPL-Drive/{0}/{1}/{2}"
      parameters:
        - *start
        - mapping:
            exam: Examens
            test: Interros
          key:
            arg: type
        - path_format: "{0}_{1}/{4}{5}-{0}-{1}{2}{3}.pdf"
          parameters:
          - arg: year
          - arg: month
          - mapping:
              All: ''
              Mineure: -Mineure
              Majeure: -Majeure
            key:
              arg: minmaj
          - arg: sol
          - arg: option
          - arg: code
